version: "3"
services:
  web:
    build: './d8'
    container_name: "d8_web"
    ports:
      - 80:80
    environment:
      - DB_HOST=postgres
      - DB_NAME=d8
      - DB_USER_NAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./d8/modules:/var/www/html/sites/default/modules
      - ./d8/info.php:/var/www/html/info.php
      - ./d8/composer.json:/var/www/html/composer.json
      # - ./d8/drupal-nodejs:/var/www/html/drupal-nodejs
      - ./d8/settings.php:/var/www/html/sites/default/settings.php
      # - ./d8/vendor:/var/www/html/vendor
      # - ./d8/share:/var/www/html/share
      - ./d8/php.ini:/usr/local/etc/php/php.ini

      # chat
      # - ./d8/chat.html:/var/www/html/chat.html
      # - ./d8/node_modules:/var/www/html/node_modules
    restart: always
  nodejs:
    build: './nodejs'
    container_name: "nodejs_web"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9231:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "." 
    volumes:
      - ./nodejs:/usr/src/app
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: d8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  pgadmin:
    image: dpage/pgadmin4:3.3
    container_name: pgadmin4
    ports:
      - 7777:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    hostname: pgadmin4
    restart: always
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:  # backup mongo
      - ./mongodb:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9999:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  wmcached:
    image: wodby/memcached:1.4-2.0.0

# docker run --name d8 -d -p 8080:80 drupal:8.6.17
# docker run --name pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_USER=postgres -d -p 5432:5432 postgres:10
# docker run --name pgadmin -e PGADMIN_DEFAULT_EMAIL=root -e PGADMIN_DEFAULT_PASSWORD=root -v pgadmin:/var/lib/pgadmin/storage -d -p 7777:80 dpage/pgadmin4:3.3

# Build & Run docker
# docker build --no-cache -t {ชือ} .
# docker run --name d8  -d -p 8080:80 d8:beta-1.0

# https://medium.com/better-programming/connect-from-local-machine-to-postgresql-docker-container-f785f00461a7
# portgres เราจำเป็นต้อง exec เข้าไปสร้าง database ก่อนโดย docker exec -it {name pg} bash
# 1. psql -U postgres
# 2. CREATE DATABASE {ชือ db};

# กรณีเราไม่สามารถใช้ pgadmin connect portgres ได้เราต้อง sudo docker inspect {ชือของ postgres} จะได้ ip เพือใช้สำหรับ connect postgras ได้