<?php

/*
$uri = 'mongodb://mongo:27017';
$collection = (new MongoDB\Client($uri))->local->startup_log;
$changeStream = $collection->watch();
for ($changeStream->rewind(); true; $changeStream->next()) {
      if ( ! $changeStream->valid()) {
          continue;
      }

      $event = $changeStream->current();

      if ($event['operationType'] === 'invalidate') {
          break;
      }

      $ns = sprintf('%s.%s', $event['ns']['db'], $event['ns']['coll']);
      $id = json_encode($event['documentKey']['_id']);

      switch ($event['operationType']) {
          case 'delete':
              printf("Deleted document in %s with _id: %s\n\n", $ns, $id);
              break;

          case 'insert':
              printf("Inserted new document in %s\n", $ns);
              echo json_encode($event['fullDocument']), "\n\n";
              break;

          case 'replace':
              printf("Replaced new document in %s with _id: %s\n", $ns, $id);
              echo json_encode($event['fullDocument']), "\n\n";
              break;

          case 'update':
              printf("Updated document in %s with _id: %s\n", $ns, $id);
              echo json_encode($event['updateDescription']), "\n\n";
              break;
      }
  }
*/

function huay_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'huay/huay';
    // $attachments['#attached']['library'][] = 'mydata/socket_io';

    // $element['#attached']['js'][] = array(
    //     'data' => array('myModule' => array('basePath' => base_path())), 
    //     'type' => 'setting',
    //   );

    /*
    pass parameter to .js

    (function ($, Drupal, drupalSettings) {
        console.log(drupalSettings);

        var user = drupalSettings.user;
        console.log(user);

        var foo = drupalSettings.fluffiness.cuddlySlider.foo;
        console.log(foo);

    })(jQuery, Drupal, drupalSettings);
    */

    $configs= Drupal\config_pages\Entity\ConfigPages::config('config_nodejs');
    $nodejs_url = '';///$configs->get('field_nodejs_url')->value;
    $params = [
        'nodejs_url' => $nodejs_url,
    ];
    $attachments['#attached']['drupalSettings']['configs'] = $params;
}


/*
 * Implements hook_theme()
*/
function huay_theme($existing, $type, $theme, $path) {  
  return [
    'front-page' => [
      'variables' => [
        'role' => '',
        'params' => array(),
      ],
    ],   
    'lottery-page' => [
      'variables' => [
        'role' => '',
        'params' => array(),
      ],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 * 
 * กรณีที่เรา เพิ่ม taxonomy_term ใหม่ เราจะต้อง เพิ่มข้อมูลฟิลล์ field_id_term == $entity->id() แก้ปัญหา id ไม่เหมือนกัน dev, uat, prod
 */
function huay_taxonomy_term_insert(Drupal\Core\Entity\EntityInterface $entity) {
    $vocabularys = \Drupal\config_pages\Entity\ConfigPages::config('config_global')->get('field_taxonomy_term')->value;
    $vocabularys = explode(",", $vocabularys);

    if (in_array($entity->bundle(), $vocabularys)) {
        $id_term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($entity->id())->get('field_tid_code')->getValue()[0]['value'];

        if(empty($id_term)){
            $term = \Drupal\taxonomy\Entity\Term::load($entity->id());
            if (!empty($term)) {
                $term->field_tid_code = $entity->id();
                $term->save();
            }
        }
        
        // dpm(t('oop > @tid ',array('@tid'=>$tid))->__toString());
    }
}

