<?php
function mydata_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'mydata/mydata_key';
    // $attachments['#attached']['library'][] = 'mydata/socket_io';

    // $element['#attached']['js'][] = array(
    //     'data' => array('myModule' => array('basePath' => base_path())), 
    //     'type' => 'setting',
    //   );

    /*
    pass parameter to .js

    (function ($, Drupal, drupalSettings) {
        console.log(drupalSettings);

        var user = drupalSettings.user;
        console.log(user);

        var foo = drupalSettings.fluffiness.cuddlySlider.foo;
        console.log(foo);

    })(jQuery, Drupal, drupalSettings);
    */

    $configs= Drupal\config_pages\Entity\ConfigPages::config('cp_config');
    $field_a1 = $configs->get('field_a1')->value;
    $computed_settings = [
        'foo' => 'bar',
        'field_a1' => $field_a1,
    ];
    $attachments['#attached']['drupalSettings']['myvar'] = $computed_settings;
    $attachments['#attached']['drupalSettings']['fluffiness']['cuddlySlider'] = $computed_settings;
}
